name: VPNBOSS
options:
  bundleIdPrefix: space.vpnboss
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    CODE_SIGN_STYLE: Automatic
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
    TARGETED_DEVICE_FAMILY: "1"
packages:
  LibXray:
    url: https://github.com/wanliyunyan/LibXray
    exactVersion: 26.6.1
  Tun2SocksKit:
    url: https://github.com/EbrahimTahernejad/Tun2SocksKit
    exactVersion: 5.15.0
targets:
  VPNBOSS:
    type: application
    platform: iOS
    sources:
      - VPNBOSS
    resources:
      - VPNBOSS/Resources
    dependencies:
      - target: PacketTunnel
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: space.vpnboss.client
      PRODUCT_NAME: VPNBOSS
      INFOPLIST_FILE: VPNBOSS/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      SUPPORTS_MACCATALYST: NO
    entitlements:
      path: VPNBOSS/VPNBOSS.entitlements
  PacketTunnel:
    type: app-extension
    platform: iOS
    sources:
      - PacketTunnel
    dependencies:
      - package: LibXray
      - package: Tun2SocksKit
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: space.vpnboss.client.PacketTunnel
      PRODUCT_NAME: PacketTunnel
      INFOPLIST_FILE: PacketTunnel/Info.plist
      SKIP_INSTALL: YES
      APPLICATION_EXTENSION_API_ONLY: YES
    entitlements:
      path: PacketTunnel/PacketTunnel.entitlements
